// GAMES

export const LOAD_GAMES = 'LOAD_GAMES';
export const UNLOAD_GAMES = 'UNLOAD_GAMES';

export const CREATE_GAME_REQUESTED = 'CREATE_GAME_REQUESTED';
export const CREATE_GAME_FULFILLED = 'CREATE_GAME_FULFILLED';
export const CREATE_GAME_REJECTED = 'CREATE_GAME_REJECTED';

export const JOIN_GAME = 'JOIN_GAME';
export const LEAVE_GAME = 'LEAVE_GAME';

// USER

export const INIT_AUTH = 'INIT_AUTH';
export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

// USERS

export const LOAD_USERS = 'LOAD_USERS';
