export const LOAD_GAMES = "LOAD_GAMES";
export const UNLOAD_GAMES = "UNLOAD_GAMES";

export const CREATE_GAME_REQUESTED = "CREATE_GAME_REQUESTED";
export const CREATE_GAME_FULFILLED = "CREATE_GAME_FULFILLED";
export const CREATE_GAME_REJECTED = "CREATE_GAME_REJECTED";
