export const JOIN_GAME_REQUESTED = 'JOIN_GAME_REQUESTED';
export const JOIN_GAME_FULFILLED = 'JOIN_GAME_FULFILLED';
export const JOIN_GAME_REJECTED = 'JOIN_GAME_REJECTED';

export const LEAVE_GAME = 'LEAVE_GAME';
export const LOAD_GAME = 'LOAD_GAME';
